package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log"
	"time"
	"workspace_project/graph/model"
	"workspace_project/internal/auth"
	"workspace_project/internal/ws"

	"github.com/jackc/pgx/v5"
	"github.com/redis/go-redis/v9"
	"golang.org/x/crypto/bcrypt"
)

// Helper function for authorized acces in createtask, movetask and getBoard
func requireAuth(ctx context.Context) (string, error) {
	userID, ok := ctx.Value("userID").(string)
	if !ok {
		return "", fmt.Errorf("authentication required")
	}

	return userID, nil
}

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.NewTaskInput) (*model.Task, error) {
	//panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
	_, err1 := requireAuth(ctx)
	if err1 != nil {
		return nil, err1
	}
	key := "board:" + input.BoardID
	_, err := r.Client.Del(ctx, key).Result()
	if err != nil {
		log.Printf("cache invalidation failed for %s: %v", key, err)
	}

	var user model.User
	if input.AssigneeID != nil {
		err := r.Pool.QueryRow(ctx, "select id, name, email from users where id=$1", *input.AssigneeID).Scan(&user.ID, &user.Name, &user.Email)
		if err != nil {
			return nil, fmt.Errorf("failed to lookup assignee: %w", err)
		}
	}

	var posMax int32
	err = r.Pool.QueryRow(ctx, "select coalesce(max(position), 0) from tasks where boards_id = $1", input.BoardID).Scan(&posMax)
	if err != nil {
		return nil, fmt.Errorf("failed to get max position: %w", err)
	}
	posMax = posMax + 1

	var taskID string
	err = r.Pool.QueryRow(ctx, "insert into tasks (boards_id, title, description, status, assignee_id, position) values ($1, $2, $3, $4, $5, $6) returning id",
		input.BoardID, input.Title, input.Description, "TODO", input.AssigneeID, posMax,
	).Scan(&taskID)
	if err != nil {
		return nil, fmt.Errorf("failed to create task: %w", err)
	}

	var task model.Task
	task.ID = taskID
	task.Title = input.Title
	task.Description = input.Description
	task.Status = "TODO"
	if input.AssigneeID != nil {
		task.Assignee = &user
	}
	task.Position = posMax

	// publishing the work for pub/sub
	var event ws.BoardEvent
	event.BoardID = input.BoardID
	event.Type = "Created Task"
	event.Task = &task
	data_for_redis, err := json.Marshal(event)
	if err != nil {
		log.Printf("failed to marshal event for board %s: %v", input.BoardID, err)
	} else {
		if err := r.Client.Publish(ctx, "board:"+input.BoardID, data_for_redis).Err(); err != nil {
			log.Printf("failed to marshal event for board %s: %v", input.BoardID, err)
		}
	}
	return &task, nil
}

// MoveTask is the resolver for the moveTask field.
func (r *mutationResolver) MoveTask(ctx context.Context, taskID string, newStatus string, newPosition int32) (*model.Task, error) {
	//panic(fmt.Errorf("not implemented: MoveTask - moveTask"))
	_, err1 := requireAuth(ctx)
	if err1 != nil {
		return nil, err1
	}
	var task model.Task
	task.ID = taskID
	var assigneeID *string
	var board_id string
	err := r.Pool.QueryRow(ctx, "update tasks set status=$1, position=$2, updated_at=now() where id=$3 returning assignee_id, title, description, status, position, boards_id", newStatus, newPosition, taskID).Scan(&assigneeID, &task.Title, &task.Description, &task.Status, &task.Position, &board_id)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("task not found: %s", taskID)
		}
		return nil, fmt.Errorf("failed to update task: %w", err)
	}

	key := "board:" + board_id
	_, err = r.Client.Del(ctx, key).Result()
	if err != nil {
		log.Printf("cache invalidation failed for %s: %v", key, err)
	}
	var user model.User
	if assigneeID != nil {
		err = r.Pool.QueryRow(ctx, "select id, name, email from users where id=$1", *assigneeID).Scan(&user.ID, &user.Name, &user.Email)
		if err != nil {
			return nil, fmt.Errorf("failed to look up assignee: %w", err)
		}
	}
	if assigneeID != nil {
		task.Assignee = &user
	}

	// For publishing
	var event ws.BoardEvent
	event.BoardID = board_id
	event.Type = "Moved Task"
	event.Task = &task
	data_for_redis, err := json.Marshal(&event)
	if err != nil {
		log.Printf("failed to marshal event for board %s: %v", event.BoardID, err)
	} else {
		if err := r.Client.Publish(ctx, "board:"+event.BoardID, data_for_redis).Err(); err != nil {
			log.Printf("failed to marshal event for board %s: %v", event.BoardID, err)
		}
	}
	return &task, nil
}

// Signup is the resolver for the signup field.
func (r *mutationResolver) Signup(ctx context.Context, input model.SignupInput) (*model.AuthpayLoad, error) {
	// panic(fmt.Errorf("not implemented: Signup - signup"))
	hash_password, err := bcrypt.GenerateFromPassword([]byte(input.Password), bcrypt.DefaultCost)
	if err != nil {
		return nil, fmt.Errorf("internal error: %w", err)
	}
	var user_id string
	err = r.Pool.QueryRow(ctx, "insert into users (email, password_hash, name) values ($1, $2, $3) returning id", input.Email, string(hash_password), input.Name).Scan(&user_id)
	if err != nil {
		return nil, fmt.Errorf("failed to create user")
	}

	var user model.User
	user.ID = user_id
	user.Email = input.Email
	user.Name = input.Name

	var Auth model.AuthpayLoad
	Auth.User = &user

	//Generating token
	token, err := auth.GenerateToken(user_id)
	if err != nil {
		return nil, fmt.Errorf("failed to generate token")
	}
	Auth.Token = token

	return &Auth, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthpayLoad, error) {
	// panic(fmt.Errorf("not implemented: Login - login"))

	var user model.User
	user.Email = email

	var actualPassword string
	err := r.Pool.QueryRow(ctx, "select id, name, password_hash from users where email = $1", email).Scan(&user.ID, &user.Name, &actualPassword)
	if err != nil {
		return nil, fmt.Errorf("invalid credentials")
	}

	err = bcrypt.CompareHashAndPassword([]byte(actualPassword), []byte(password))
	if err != nil {
		return nil, fmt.Errorf("invalid credentials")
	}

	var Auth model.AuthpayLoad
	Auth.User = &user

	token, err := auth.GenerateToken(user.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to generate token: %w", err)
	}
	Auth.Token = token

	return &Auth, nil
}

// GetBoard is the resolver for the getBoard field.
func (r *queryResolver) GetBoard(ctx context.Context, id string) (*model.Board, error) {
	//panic(fmt.Errorf("not implemented: GetBoard - getBoard"))
	_, err1 := requireAuth(ctx)
	if err1 != nil {
		return nil, err1
	}
	var board model.Board
	// Deciding a consistent key : board:<id> here boards_id
	//This will be our cache key (A simple concatinated string)
	key := "board:" + id
	val, err := r.Client.Get(ctx, key).Result()
	if err == nil {
		err1 := json.Unmarshal([]byte(val), &board)
		if err1 != nil {
			return nil, fmt.Errorf("failed to unmarshal: %w", err1)
		}

		return &board, nil
	} else if errors.Is(err, redis.Nil) {

	} else {
		// real redis error
		return nil, fmt.Errorf("cache lookup failed")
	}
	var boardTitle string
	err = r.Pool.QueryRow(ctx, "select title from boards where id=$1", id).Scan(&boardTitle)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("board not found: %s", id)
		}
		return nil, fmt.Errorf("failed to load board: %w", err)
	}

	rows, err := r.Pool.Query(ctx, "select id, title, description, status, assignee_id, position from tasks where boards_id=$1", id)
	if err != nil {
		return nil, fmt.Errorf("database failure: %w", err)
	}
	defer rows.Close()

	for rows.Next() {
		var temp model.Task
		var assigneeID *string

		err = rows.Scan(&temp.ID, &temp.Title, &temp.Description, &temp.Status, &assigneeID, &temp.Position)
		if err != nil {
			return nil, err
		}
		if assigneeID != nil {
			var user model.User
			err := r.Pool.QueryRow(ctx, "select id, name, email from users where id=$1", *assigneeID).Scan(&user.ID, &user.Name, &user.Email)
			if err != nil {
				return nil, fmt.Errorf("assignee lookup failed: %w", err)
			}

			temp.Assignee = &user
		}

		board.Tasks = append(board.Tasks, &temp)
	}

	board.Title = boardTitle
	board.ID = id

	data_for_Redis, err := json.Marshal(&board)
	if err != nil {
		return nil, fmt.Errorf("failed to Marshal: %w", err)
	}

	_, err = r.Client.Set(ctx, key, data_for_Redis, 5*time.Minute).Result() // 5min of expiration time
	if err != nil {
		fmt.Printf("failed to cache board %s:%v", id, err)
	}
	return &board, nil
}

// BoardUpdated is the resolver for the boardUpdated field.
/*
suppose we have 2 users viewing the same board so we can say these are listeners ,
now say a 3rd user logins for same board and updates it .
So the 3rd user becomes a publisher and now we need to update the board for the other users
For this purpose we use redis pub/sub feature (built-in redis)
*/

// Now YOUR code has to find which local WebSocket connections
// are watching board 123, and push the update to each one
func (r *subscriptionResolver) BoardUpdated(ctx context.Context, boardID string) (<-chan *model.Task, error) {
	// panic(fmt.Errorf("not implemented: BoardUpdated - boardUpdated"))
	_, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	c := &ws.Client{
		BoardID: boardID,
		Send:    make(chan ws.BoardEvent, 8),
	}

	r.Hub.Register(c)

	ch := make(chan *model.Task)

	go func() {
		defer r.Hub.Unregister(c)
		defer close(ch)

		for {
			select {
			case event, ok := <-c.Send:
				if !ok {
					return
				}
				select {
				case ch <- event.Task:
				case <-ctx.Done():
					return
				}
			case <-ctx.Done():
				return
			}
		}
	}()

	return ch, nil

}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type (
	mutationResolver     struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
