// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthpayLoad struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Board struct {
	ID    string  `json:"id"`
	Title string  `json:"title"`
	Tasks []*Task `json:"tasks"`
}

type Mutation struct {
}

type NewTaskInput struct {
	BoardID     string  `json:"boardId"`
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	AssigneeID  *string `json:"assigneeId,omitempty"`
}

type Query struct {
}

type SignupInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Name     string `json:"name"`
}

type Subscription struct {
}

type Task struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	Status      string  `json:"status"`
	Assignee    *User   `json:"assignee,omitempty"`
	Position    int32   `json:"position"`
}

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
